pipeline {
    agent 'docker'

    environment {
        DOCKERHUB_REPO = "rajesh984"
    }

    stages {

        stage('Build Images') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_REPO/onlineboutique-frontend:${BUILD_NUMBER} src/frontend

                docker build -t $DOCKERHUB_REPO/onlineboutique-cartservice:${BUILD_NUMBER} src/cartservice

                docker build -t $DOCKERHUB_REPO/onlineboutique-productcatalogservice:${BUILD_NUMBER} src/productcatalogservice
                '''
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                docker push $DOCKERHUB_REPO/onlineboutique-frontend:${BUILD_NUMBER}

                docker push $DOCKERHUB_REPO/onlineboutique-cartservice:${BUILD_NUMBER}

                docker push $DOCKERHUB_REPO/onlineboutique-productcatalogservice:${BUILD_NUMBER}
                '''
            }
        }
    }

}